### ISSUE TITLE
Add git tag for v0.3.4

### ISSUE THREAD

**Issue by Builditluc** [ukmrs/smokey#27]
Hi, I would like to add smokey to the [nixpkgs](https://github.com/NixOS/nixpkgs/) repo, so that users using nix can easily add the package to their environment.

Would you mind either releasing a new version with a git tag, or creating a git tag for the v0.3.4 commit https://github.com/ukmrs/smokey/commit/f5842552b13710d299992a9aa372206105f1ae8e?

**Comment by ukmrs** [comment]
Hello!
Happy to see a contributor from 3 years ago 😄 
I added the [v0.3.4 tag](https://github.com/ukmrs/smokey/releases/tag/v0.3.4).

Cheers.

**Comment by Builditluc** [comment]
Hey, thanks!

Another note, the copying of the `storage` folder during build time causes issues for the building of the package in nix.

I'll move this into another issue, maybe we could work on a solution that doesn't need to copy the folder during build time?
